name = "StructuredArrays"
uuid = "2e8cd123-6858-488d-b42d-068777248635"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.2.8"

[deps]
ArrayTools = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"

[compat]
ArrayTools = "0.2.3, 0.3"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
